### Day Objectives:





In [8]:
s="Mahesh"
lb = 1
ub = 3

s.replace(s[lb-1:ub],s[lb-1:ub][::-1])

'haMesh'

In [ ]:


def decryptMarksData(encryptedfile, kkeyfile):
    key = dictionaryKeyFile(keyfile)
    
    newkey = {}
    for key, value in key.items():
        newkay[value]=key
    with open(encryptedfile,'r') as f:
        encrypteddata = f.read().split('\n')
        
    with open('DataFiles/decryptedMarks.txt','w') as f:
        for encryptedmark in encrypteddata:
            line = ''
            for n in encryptedmark:
                line +=newkey[n]
            f.write(line + '\n')
        

In [ ]:
# Comprehensions

keyfile = 'DataFiles/key.txt'

key = dictionaryKeyFile(keyfile)

#evenkeys={item for item in keys.item() if int(item[0])%2==0}
evenkeys= {item for in key}
evenkeys

### Numpy Library

- Used for Processing N-Dimensional arrays

In [15]:
import numpy as np

li = [1,2,3,'a']
a = np.array(li)
#type(a)
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
rn = np.random.randint(0,100,size=10)
rn

array([24, 79, 73, 53, 59, 66, 19, 37, 97, 81])

In [31]:

m3 = np.random.randint(0,3,size=(2,3,4))
m3.ndim
m3.shape
m3.size
m3.dtype
m3.itemsize

4

### Pandas

#### Use Cases
- Data Cleaning
- Data Transfermation
- Data Analysis

#### Notations
- Series
- DataFrames

In [39]:
import pandas as pd

internal1 = {'s1':21,'s2':18,'s3':24}
internal1 = pd.Series(internal1) 
internal2 = {'s1':31,'s2':28,'s3':44}
internal2 = pd.Series(internal2)
internal2

s1    31
s2    28
s3    44
dtype: int64

In [40]:
final = {'Internal1':internal1,'Internal2':internal2}
final = pd.DataFrame(final)

final

Internal1  Internal2
s1         21         31
s2         18         28
s3         24         44

In [42]:
final['Internal1']

s1    21
s2    18
s3    24
Name: Internal1, dtype: int64

In [43]:
final.columns # names of columns

Index(['Internal1', 'Internal2'], dtype='object')

In [44]:
final.values # Lists of all rows

array([[21, 31],
       [18, 28],
       [24, 44]], dtype=int64)

In [46]:
final.values[2]

array([24, 44], dtype=int64)

In [50]:
# final.values[2,1] 
final.values[2][1] 

44

In [49]:
final.values.shape

(3, 2)

In [52]:
for row in final.values:
    print('Internal1 - ',row[0],', Internal2 -',row[1])


Internal1 -  21 , Internal2 - 31
Internal1 -  18 , Internal2 - 28
Internal1 -  24 , Internal2 - 44


In [53]:
final

Internal1  Internal2
s1         21         31
s2         18         28
s3         24         44

In [57]:
final.loc['s4']=[24,56]
final

Internal1  Internal2
s1         21         31
s2         18         28
s3         24         44
s4         24         56

In [65]:
final.drop('s3')

Internal1  Internal2
s1         21         31
s2         18         28
s4         24         56

In [63]:
final

Internal1  Internal2
s1         21         31
s2         18         28
s3         24         44
s4         24         56

In [67]:
final.values[2]=[42,44]
final

Internal1  Internal2
s1         21         31
s2         18         28
s3         42         44
s4         24         56

In [73]:
# reading csv file data
import pandas as pd
filepath = 'DataFiles/income.csv'
incomedf = pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [75]:
for row in incomedf.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [78]:
# average income of a perticular state Arizona
sum = 0
for i in range(2,11):
    sum += incomedf.values[2][i]
sum/len(incomedf.values[2][2:])

47214.77777777778

In [84]:
sm =0 
for i in incomedf.values:
    sum += i[-2]
sum/len(incomedf.values)

235103.0